[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/"
restartPolicyType = "on_failure"

[[build.steps]]
name = "InstallSystemDependencies"
command = """
apt-get update && \
apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libgstreamer1.0-0 \
    python3-opencv \
    ffmpeg
"""